OverwriteModelError: Cannot overwrite `User` model once compiled.
Mongoose error of some sort. Error generated on after successfully running a test and then saving the next file, even though the test doesn't call on the model. Needed to make an adjustment in the model itself:

Also, created small test exercise to use bcrypt asyn methods